### ISSUE TITLE
Resolve the "Mismatch in telemetry between aca_l0 and cheta" failures

### ISSUE THREAD

**Issue by taldcroft** [sot/agasc#70]
As @jeanconn nicely documented, most (or all?) of those cases are related to a safing action that resulted in a Kalman dwell being interrupted.

- The star-obs where these occur is not included in the report itself, I guess because of the failure.

Would it be possible to just use the available intersection of L0 images and cheta telemetry instead of raising an exception?
```
    if len(telem['AOACASEQ']) != len(telem['IMGSIZE']):
        raise MagStatsException(
            "Mismatch in telemetry between aca_l0 and cheta",
            agasc_id=obs['agasc_id'], obsid=obs['obsid'], timeline_id=obs['timeline_id']
        )
```
Basically just carry on with whatever is there, and apply the existing criteria for whether a star-obs is OK. In most of the cases of a safing action, there is actually useful ACA image data available.

**Comment by javierggt** [comment]
Currently, all OBSIDs with safe/normal suns trigger the `Mismatch in telemetry between aca_l0 and cheta` exception. The reason is trivial, the exception is raised when the number of entries from aca_l0 slot data is different that the number of entries from cheta (after matching their times). safe/normal suns are currently being removed from telemetry using cheta, but they are not removed from slot data. Therefore, their number of entries always differ.

The following OBSIDs give the error if normal suns and safe suns are not removed, so they are the ones this exception was meant to catch:
- 5806
- 6615

I just tested, and I can confirm that the error is not triggered if I use `fetch.Msidset` instead of `fetch.MSIDset`.

This means that the original error stems from bad quality data which is not removed in `fetch.MSIDset` but is removed in `fetch.Msidset`. If the bad-quality data is not removed, time is not monotonically increasing, which causes duplicate times (therefore more entries from cheta).
